import JSZip from 'jszip';
import { NotebookOutputItem, DocxConfig } from '../types/notebook';
import { computeIntelligentLayout } from './intelligentGrid';

// XML 1.0 valid character filter
export function xmlSafe(s: string): string {
  const str = String(s ?? '');
  let out = '';
  for (let i = 0; i < str.length; i++) {
    const cp = str.codePointAt(i);
    if (
      cp === 9 ||
      cp === 10 ||
      cp === 13 ||
      (cp && cp >= 0x20 && cp <= 0xd7ff) ||
      (cp && cp >= 0xe000 && cp <= 0xfffd) ||
      (cp && cp >= 0x10000 && cp <= 0x10ffff)
    ) {
      out += String.fromCodePoint(cp);
    }
    if (cp && cp > 0xffff) i++;
  }
  return out;
}

export function escXml(s: string): string {
  return xmlSafe(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function dataUriParts(dataUrl: string): { mime: string; b64: string } {
  const comma = dataUrl.indexOf(',');
  const head = dataUrl.slice(0, comma);
  const b64 = dataUrl.slice(comma + 1);
  const mime = (head.match(/^data:([^;]+)/) || [])[1] || 'image/png';
  return { mime, b64 };
}

function wordText(
  text: string,
  bold = false,
  size = 22,
  color = '1F2937',
  align: 'center' | 'left' | 'right' | null = null,
  font = 'Aptos',
  spaceAfter = 140
): string {
  const pPr = `<w:pPr>${align ? `<w:jc w:val="${align}"/>` : ''}<w:spacing w:after="${spaceAfter}"/></w:pPr>`;
  const rPr = `<w:rPr><w:rFonts w:ascii="${font}" w:hAnsi="${font}"/>${bold ? '<w:b/>' : ''}${
    size ? `<w:sz w:val="${size}"/><w:szCs w:val="${size}"/>` : ''
  }${color ? `<w:color w:val="${color}"/>` : ''}</w:rPr>`;
  return `<w:p>${pPr}<w:r>${rPr}<w:t xml:space="preserve">${escXml(text)}</w:t></w:r></w:p>`;
}

function wordPageBreak(): string {
  return '<w:p><w:r><w:br w:type="page"/></w:r></w:p>';
}

function wordDivider(): string {
  return '<w:p><w:pPr><w:pBdr><w:bottom w:val="single" w:sz="6" w:space="8" w:color="E2E8F0"/></w:pBdr><w:spacing w:after="240"/></w:pPr></w:p>';
}

function wordImage(relId: string, wPt: number, hPt: number, index: number): string {
  // Convert points to EMUs: 1 pt = 12700 EMUs
  const cx = Math.round(wPt * 12700);
  const cy = Math.round(hPt * 12700);
  const docPrId = 1000 + index;

  return `<w:p><w:pPr><w:jc w:val="center"/><w:spacing w:after="200"/></w:pPr><w:r><w:drawing>
  <wp:inline distT="0" distB="0" distL="0" distR="0">
    <wp:extent cx="${cx}" cy="${cy}"/>
    <wp:docPr id="${docPrId}" name="OutputFigure_${index}"/>
    <wp:cNvGraphicFramePr><a:graphicFrameLocks noChangeAspect="1"/></wp:cNvGraphicFramePr>
    <a:graphic>
      <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
        <pic:pic>
          <pic:nvPicPr><pic:cNvPr id="${docPrId}" name="OutputFigure_${index}"/><pic:cNvPicPr preferRelativeResize="0"/></pic:nvPicPr>
          <pic:blipFill>
            <a:blip r:embed="${relId}"/>
            <a:stretch><a:fillRect/></a:stretch>
          </pic:blipFill>
          <pic:spPr>
            <a:xfrm><a:off x="0" y="0"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm>
            <a:prstGeom prst="rect"><a:avLst/></a:prstGeom>
          </pic:spPr>
        </pic:pic>
      </a:graphicData>
    </a:graphic>
  </wp:inline>
  </w:drawing></w:r></w:p>`;
}

export async function generateDocxBlob(
  items: NotebookOutputItem[],
  config: DocxConfig,
  notebookFilename: string,
  onProgress?: (percent: number, statusText: string) => void
): Promise<Blob> {
  const activeItems = items.filter((item) => item.selected !== false);
  if (activeItems.length === 0) {
    throw new Error('No items selected for export. Please select at least one output figure.');
  }

  onProgress?.(10, 'Encoding figures and formatting document...');

  let bodyXml = '';
  const media: Array<{ name: string; bytes: Uint8Array; relId: string }> = [];
  const font = config.fontFamily || 'Aptos';
  const autoLayout = config.autoLayout || 'single-column';
  const isSideBySide = autoLayout === 'side-by-side';

  // Template accent color
  const tplAccent =
    config.template === 'executive-summary'
      ? '0F172A'
      : config.template === 'academic-paper'
      ? '1E293B'
      : '1E3A8A';

  // Title / Cover Page
  if (config.titlePage) {
    bodyXml += wordText('', false, 60, '000000', null, font, 720); // Top spacer
    bodyXml += wordText(config.reportTitle || 'Notebook Outputs Report', true, 44, tplAccent, 'center', font, 180);
    if (config.reportSubtitle) {
      bodyXml += wordText(config.reportSubtitle, false, 24, '475569', 'center', font, 240);
    }
    bodyXml += wordDivider();
    bodyXml += wordText(`Notebook Source: ${notebookFilename}`, true, 20, tplAccent, 'center', font, 120);
    if (config.authorName) {
      bodyXml += wordText(`Generated by: ${config.authorName}`, false, 18, '64748B', 'center', font, 120);
    }
    const dateStr = config.reportDate || new Date().toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    bodyXml += wordText(`Export Date: ${dateStr}`, false, 18, '94A3B8', 'center', font, 480);
    bodyXml += wordText(
      `Extracted ${activeItems.length} validated output object${activeItems.length === 1 ? '' : 's'} (${autoLayout === 'side-by-side' ? 'Side-by-Side Auto-Layout' : 'Single-Column Auto-Layout'})`,
      false,
      16,
      '64748B',
      'center',
      font,
      240
    );
    bodyXml += wordPageBreak();
  }

  // Helper to package media and compute dimensions
  const processItemMedia = async (item: NotebookOutputItem, idx: number, maxW: number, maxH: number) => {
    if (!item.src) {
      throw new Error(`Output #${idx + 1} (${item.caption}) has no rendered image data.`);
    }

    const { mime, b64 } = dataUriParts(item.src);
    const ext = mime.includes('jpeg') || mime.includes('jpg') ? 'jpg' : 'png';
    const relId = `rIdImg${idx + 1}`;
    const name = `output_${String(idx + 1).padStart(3, '0')}.${ext}`;

    let bytes: Uint8Array;
    try {
      bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
    } catch {
      throw new Error(`Failed to decode image data for Figure ${idx + 1}.`);
    }

    if (bytes.length === 0) {
      throw new Error(`Figure ${idx + 1} contains zero image bytes.`);
    }

    media.push({ name, bytes, relId });

    const w = item.dim?.w || 800;
    const h = item.dim?.h || 500;
    const ratio = Math.max(0.01, h / w);

    let finalW = maxW;
    let finalH = Math.round(finalW * ratio);
    if (finalH > maxH) {
      finalH = maxH;
      finalW = Math.round(finalH / ratio);
    }

    return { relId, finalW, finalH };
  };

  // Helper to build content XML for an item
  const buildItemXml = (item: NotebookOutputItem, idx: number, relId: string, finalW: number, finalH: number, compact: boolean) => {
    let itemXml = '';
    const figNum = String(idx + 1).padStart(2, '0');
    const label = `Figure ${figNum}: ${item.caption || 'Output'}`;

    if (config.labelCaption) {
      itemXml += wordText(label, true, compact ? 20 : 22, tplAccent, 'left', font, 60);
    }

    if (config.addCellRef) {
      const execPart = item.executionCount !== null ? ` · Exec [${item.executionCount}]` : '';
      const meta = `Cell ${item.cellIndex + 1}, Out #${item.outputIndex + 1}${execPart} · ${item.subtype || item.outputType}`;
      itemXml += wordText(meta, false, compact ? 14 : 15, '64748B', 'left', font, 60);
    }

    const itemMetaParts: string[] = [];
    if (item.author) itemMetaParts.push(`Author: ${item.author}`);
    if (item.reportDate) itemMetaParts.push(`Date: ${item.reportDate}`);
    if (item.sectionTag) itemMetaParts.push(`[${item.sectionTag}]`);
    if (itemMetaParts.length > 0) {
      itemXml += wordText(itemMetaParts.join(' · '), false, compact ? 13 : 15, '475569', 'left', font, 80);
    }

    if (item.notes && item.notes.trim()) {
      itemXml += wordText(item.notes.trim(), false, compact ? 15 : 16, '334155', 'left', font, 100);
    }

    itemXml += wordImage(relId, finalW, finalH, idx + 1);
    return itemXml;
  };

  if (config.intelligentGrid) {
    // ---------------------------------------------------------
    // INTELLIGENT GRID PACKING (Aspect-ratio aware density layout)
    // Wide/hero figures span full width, balanced figures pair side-by-side
    // ---------------------------------------------------------
    const layout = computeIntelligentLayout(activeItems, config);
    const colMaxW = 220;
    const colMaxH = 280;
    const maxW = 460;
    const maxH = 540;

    for (let rIdx = 0; rIdx < layout.rows.length; rIdx++) {
      const row = layout.rows[rIdx];
      onProgress?.(
        15 + Math.round(((rIdx + 1) / layout.rows.length) * 60),
        `Intelligent packing row ${rIdx + 1} of ${layout.rows.length}...`
      );
      await new Promise((resolve) => setTimeout(resolve, 25));

      if (row.type === 'single') {
        const item = row.items[0];
        const itemIdx = activeItems.indexOf(item);
        const effectiveIdx = itemIdx >= 0 ? itemIdx : rIdx;
        const { relId, finalW, finalH } = await processItemMedia(item, effectiveIdx, maxW, maxH);
        bodyXml += buildItemXml(item, effectiveIdx, relId, finalW, finalH, false);
      } else {
        const itemA = row.items[0];
        const itemB = row.items[1];
        const idxA = activeItems.indexOf(itemA);
        const idxB = activeItems.indexOf(itemB);
        const effA = idxA >= 0 ? idxA : rIdx * 2;
        const effB = idxB >= 0 ? idxB : rIdx * 2 + 1;

        const mediaA = await processItemMedia(itemA, effA, colMaxW, colMaxH);
        const cellAContent = buildItemXml(itemA, effA, mediaA.relId, mediaA.finalW, mediaA.finalH, true);

        let cellBContent = '<w:p><w:pPr><w:spacing w:after="100"/></w:pPr></w:p>';
        if (itemB) {
          const mediaB = await processItemMedia(itemB, effB, colMaxW, colMaxH);
          cellBContent = buildItemXml(itemB, effB, mediaB.relId, mediaB.finalW, mediaB.finalH, true);
        }

        bodyXml += `<w:tbl>
  <w:tblPr>
    <w:tblW w:w="9360" w:type="dxa"/>
    <w:jc w:val="center"/>
    <w:tblBorders>
      <w:top w:val="none"/><w:left w:val="none"/><w:bottom w:val="none"/><w:right w:val="none"/>
      <w:insideH w:val="none"/><w:insideV w:val="none"/>
    </w:tblBorders>
    <w:tblCellMar>
      <w:top w:w="120" w:type="dxa"/><w:bottom w:w="120" w:type="dxa"/>
      <w:left w:w="120" w:type="dxa"/><w:right w:w="120" w:type="dxa"/>
    </w:tblCellMar>
  </w:tblPr>
  <w:tblGrid>
    <w:gridCol w:w="4680"/>
    <w:gridCol w:w="4680"/>
  </w:tblGrid>
  <w:tr>
    <w:trPr><w:cantSplit/></w:trPr>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="4680" w:type="dxa"/>
        <w:vAlign w:val="top"/>
      </w:tcPr>
      ${cellAContent}
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="4680" w:type="dxa"/>
        <w:vAlign w:val="top"/>
      </w:tcPr>
      ${cellBContent}
    </w:tc>
  </w:tr>
</w:tbl>`;
      }

      if (config.addPageBreaks && rIdx < layout.rows.length - 1) {
        bodyXml += wordPageBreak();
      } else if (rIdx < layout.rows.length - 1) {
        bodyXml += wordDivider();
      }
    }
  } else if (isSideBySide) {
    // ---------------------------------------------------------
    // SIDE-BY-SIDE AUTO-LAYOUT (2 figures per row in Word table)
    // ---------------------------------------------------------
    const colMaxW = 220; // pt width per column (approx 3.05 inches)
    const colMaxH = 280; // pt max height per figure

    for (let i = 0; i < activeItems.length; i += 2) {
      const itemA = activeItems[i];
      const itemB = i + 1 < activeItems.length ? activeItems[i + 1] : null;

      onProgress?.(
        15 + Math.round(((i + 1) / activeItems.length) * 60),
        `Packaging side-by-side figures ${i + 1}${itemB ? ` and ${i + 2}` : ''} of ${activeItems.length}...`
      );
      await new Promise((resolve) => setTimeout(resolve, 25));

      const mediaA = await processItemMedia(itemA, i, colMaxW, colMaxH);
      const cellAContent = buildItemXml(itemA, i, mediaA.relId, mediaA.finalW, mediaA.finalH, true);

      let cellBContent = '<w:p><w:pPr><w:spacing w:after="100"/></w:pPr></w:p>';
      if (itemB) {
        const mediaB = await processItemMedia(itemB, i + 1, colMaxW, colMaxH);
        cellBContent = buildItemXml(itemB, i + 1, mediaB.relId, mediaB.finalW, mediaB.finalH, true);
      }

      bodyXml += `<w:tbl>
  <w:tblPr>
    <w:tblW w:w="9360" w:type="dxa"/>
    <w:jc w:val="center"/>
    <w:tblBorders>
      <w:top w:val="none"/><w:left w:val="none"/><w:bottom w:val="none"/><w:right w:val="none"/>
      <w:insideH w:val="none"/><w:insideV w:val="none"/>
    </w:tblBorders>
    <w:tblCellMar>
      <w:top w:w="120" w:type="dxa"/><w:bottom w:w="120" w:type="dxa"/>
      <w:left w:w="120" w:type="dxa"/><w:right w:w="120" w:type="dxa"/>
    </w:tblCellMar>
  </w:tblPr>
  <w:tblGrid>
    <w:gridCol w:w="4680"/>
    <w:gridCol w:w="4680"/>
  </w:tblGrid>
  <w:tr>
    <w:trPr><w:cantSplit/></w:trPr>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="4680" w:type="dxa"/>
        <w:vAlign w:val="top"/>
      </w:tcPr>
      ${cellAContent}
    </w:tc>
    <w:tc>
      <w:tcPr>
        <w:tcW w:w="4680" w:type="dxa"/>
        <w:vAlign w:val="top"/>
      </w:tcPr>
      ${cellBContent}
    </w:tc>
  </w:tr>
</w:tbl>`;

      if (config.addPageBreaks && i + 2 < activeItems.length) {
        bodyXml += wordPageBreak();
      } else if (i + 2 < activeItems.length) {
        bodyXml += wordDivider();
      }
    }
  } else {
    // ---------------------------------------------------------
    // SINGLE-COLUMN AUTO-LAYOUT (Standard full-width figures)
    // ---------------------------------------------------------
    const maxW = 460;
    const maxH = 540;

    for (let i = 0; i < activeItems.length; i++) {
      const item = activeItems[i];
      onProgress?.(
        15 + Math.round(((i + 1) / activeItems.length) * 60),
        `Processing figure ${i + 1} of ${activeItems.length}: ${item.caption || 'Output figure'}...`
      );
      await new Promise((resolve) => setTimeout(resolve, 25));

      const { relId, finalW, finalH } = await processItemMedia(item, i, maxW, maxH);
      bodyXml += buildItemXml(item, i, relId, finalW, finalH, false);

      if (config.addPageBreaks && i < activeItems.length - 1) {
        bodyXml += wordPageBreak();
      } else if (i < activeItems.length - 1) {
        bodyXml += wordDivider();
      }
    }
  }

  onProgress?.(80, 'Creating OpenXML package and relations...');

  const zip = new JSZip();

  const contentTypes = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Default Extension="png" ContentType="image/png"/>
  <Default Extension="jpg" ContentType="image/jpeg"/>
  <Default Extension="jpeg" ContentType="image/jpeg"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
  <Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/>
</Types>`;

  const rootRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>`;

  let docRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">`;
  media.forEach((m) => {
    docRels += `<Relationship Id="${m.relId}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/${m.name}"/>`;
  });
  docRels += '</Relationships>';

  const styles = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:docDefaults>
    <w:rPrDefault><w:rPr><w:rFonts w:ascii="${font}" w:hAnsi="${font}"/></w:rPr></w:rPrDefault>
  </w:docDefaults>
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal">
    <w:name w:val="Normal"/>
    <w:rPr><w:rFonts w:ascii="${font}" w:hAnsi="${font}"/><w:sz w:val="22"/><w:color w:val="1E293B"/></w:rPr>
  </w:style>
</w:styles>`;

  const settings = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:zoom w:val="100"/>
  <w:defaultTabStop w:val="720"/>
  <w:compat><w:compatSetting w:name="compatibilityMode" w:uri="http://schemas.microsoft.com/office/word" w:val="15"/></w:compat>
</w:settings>`;

  const coreProps = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:dcterms="http://purl.org/dc/terms/"
  xmlns:dcmitype="http://purl.org/dc/dcmitype/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>${escXml(config.reportTitle || 'Notebook Outputs Report')}</dc:title>
  <dc:creator>${escXml(config.authorName || 'Colab2Doc')}</dc:creator>
  <cp:lastModifiedBy>Colab2Doc</cp:lastModifiedBy>
  <dcterms:created xsi:type="dcterms:W3CDTF">${new Date().toISOString()}</dcterms:created>
</cp:coreProperties>`;

  const appProps = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"
  xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>Colab2Doc Word Generator</Application>
  <DocSecurity>0</DocSecurity>
  <ScaleCrop>false</ScaleCrop>
  <Company>Colab2Doc</Company>
  <LinksUpToDate>false</LinksUpToDate>
  <SharedDoc>false</SharedDoc>
  <HyperlinksChanged>false</HyperlinksChanged>
  <AppVersion>16.0000</AppVersion>
</Properties>`;

  // Standard letter page with 0.8 in margins (1152 twips)
  const sectPr = `<w:sectPr>
    <w:pgSz w:w="12240" w:h="15840"/>
    <w:pgMar w:top="1080" w:right="1080" w:bottom="1080" w:left="1080"/>
  </w:sectPr>`;

  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
  xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">
  <w:body>${bodyXml}${sectPr}</w:body>
</w:document>`;

  zip.file('[Content_Types].xml', contentTypes);
  zip.folder('_rels')?.file('.rels', rootRels);
  const docProps = zip.folder('docProps');
  docProps?.file('core.xml', coreProps);
  docProps?.file('app.xml', appProps);

  const wordFolder = zip.folder('word');
  wordFolder?.file('document.xml', documentXml);
  wordFolder?.file('styles.xml', styles);
  wordFolder?.file('settings.xml', settings);
  wordFolder?.folder('_rels')?.file('document.xml.rels', docRels);

  const mediaFolder = wordFolder?.folder('media');
  for (const m of media) {
    mediaFolder?.file(m.name, m.bytes, { binary: true });
  }

  onProgress?.(80, 'Compressing OpenXML package and embedding binary images...');
  await new Promise((resolve) => setTimeout(resolve, 20));

  const blob = await zip.generateAsync(
    {
      type: 'blob',
      mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    },
    (metadata) => {
      const p = 80 + Math.round((metadata.percent / 100) * 14);
      onProgress?.(p, `Compressing OpenXML archive: ${Math.round(metadata.percent)}%...`);
    }
  );

  onProgress?.(95, 'Validating DOCX package integrity and OpenXML schemas...');
  await new Promise((resolve) => setTimeout(resolve, 40));

  // Self-verification check: reopen and verify entries
  const verifyZip = await JSZip.loadAsync(blob);
  const docEntry = verifyZip.file('word/document.xml');
  const relEntry = verifyZip.file('word/_rels/document.xml.rels');
  if (!docEntry || !relEntry) {
    throw new Error('DOCX integrity check failed: missing main document or relationships.');
  }

  const relText = await relEntry.async('text');
  for (const m of media) {
    const fileEntry = verifyZip.file('word/media/' + m.name);
    if (!fileEntry) {
      throw new Error(`Integrity check failed: missing media file ${m.name}.`);
    }
    if (!relText.includes(`Id="${m.relId}"`)) {
      throw new Error(`Integrity check failed: missing relation Id ${m.relId} for ${m.name}.`);
    }
  }

  onProgress?.(100, `Successfully generated and verified ${media.length} figures.`);
  return blob;
}

export async function exportImagesAsZip(
  items: NotebookOutputItem[],
  zipFilename: string,
  onProgress?: (percent: number, statusText: string) => void
): Promise<Blob> {
  const activeItems = items.filter((item) => item.selected !== false);
  const zip = new JSZip();

  for (let i = 0; i < activeItems.length; i++) {
    const item = activeItems[i];
    onProgress?.(
      Math.round(((i + 1) / activeItems.length) * 90),
      `Packaging image ${i + 1} of ${activeItems.length}...`
    );

    const { mime, b64 } = dataUriParts(item.src);
    const ext = mime.includes('jpeg') || mime.includes('jpg') ? 'jpg' : 'png';
    const cleanCaption = (item.caption || 'output')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .slice(0, 40);
    const filename = `fig_${String(i + 1).padStart(2, '0')}_${cleanCaption}.${ext}`;

    const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
    zip.file(filename, bytes, { binary: true });
  }

  onProgress?.(95, 'Compressing ZIP archive...');
  return await zip.generateAsync({ type: 'blob' });
}
