import { jsPDF } from 'jspdf';
import { NotebookOutputItem, DocxConfig } from '../types/notebook';
import { computeIntelligentLayout } from './intelligentGrid';

export async function generatePdfBlob(
  items: NotebookOutputItem[],
  config: DocxConfig,
  notebookFilename: string,
  onProgress?: (percent: number, statusText: string) => void
): Promise<Blob> {
  const active = items.filter((i) => i.selected !== false);
  if (active.length === 0) {
    throw new Error('No items selected for PDF generation');
  }

  // Create jsPDF instance (A4 portrait: 210 x 297 mm, pt units: 595.28 x 841.89 pt)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;

  // Template accent color RGB
  const accentRgb: [number, number, number] =
    config.template === 'executive-summary'
      ? [15, 23, 42] // Slate 900
      : config.template === 'academic-paper'
      ? [30, 41, 59] // Slate 800
      : [30, 58, 138]; // Blue 900

  const autoLayout = config.autoLayout || 'single-column';
  const isSideBySide = autoLayout === 'side-by-side';

  let pageNum = 1;

  // 1. Cover / Title Page (if config.titlePage)
  if (config.titlePage) {
    onProgress?.(10, 'Creating PDF Title Page...');
    // Modern accent header bar
    doc.setFillColor(accentRgb[0], accentRgb[1], accentRgb[2]);
    doc.rect(0, 0, pageWidth, 10, 'F');

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(accentRgb[0], accentRgb[1], accentRgb[2]);
    const titleLines = doc.splitTextToSize(config.reportTitle || 'Notebook Outputs Report', contentWidth);
    doc.text(titleLines, margin, 160);

    let currentY = 160 + titleLines.length * 28;

    // Subtitle
    if (config.reportSubtitle) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(12);
      doc.setTextColor(71, 85, 105); // slate-600
      const subLines = doc.splitTextToSize(config.reportSubtitle, contentWidth);
      doc.text(subLines, margin, currentY);
      currentY += subLines.length * 16 + 12;
    } else {
      currentY += 15;
    }

    // Divider line
    doc.setDrawColor(203, 213, 225); // slate-300
    doc.setLineWidth(1.5);
    doc.line(margin, currentY, margin + 70, currentY);
    currentY += 30;

    // Metadata details
    doc.setFontSize(10.5);
    doc.setTextColor(30, 41, 59); // slate-800

    doc.setFont('helvetica', 'bold');
    doc.text('Notebook Source:', margin, currentY);
    doc.setFont('helvetica', 'normal');
    doc.text(notebookFilename || 'notebook.ipynb', margin + 120, currentY);
    currentY += 20;

    if (config.authorName) {
      doc.setFont('helvetica', 'bold');
      doc.text('Author / Team:', margin, currentY);
      doc.setFont('helvetica', 'normal');
      doc.text(config.authorName, margin + 120, currentY);
      currentY += 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.text('Date of Report:', margin, currentY);
    doc.setFont('helvetica', 'normal');
    const dateStr =
      config.reportDate ||
      new Date().toLocaleDateString(undefined, {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
    doc.text(dateStr, margin + 120, currentY);
    currentY += 20;

    doc.setFont('helvetica', 'bold');
    doc.text('Layout Mode:', margin, currentY);
    doc.setFont('helvetica', 'normal');
    doc.text(isSideBySide ? 'Side-by-Side (Dual-Column)' : 'Single-Column (Full Width)', margin + 120, currentY);
    currentY += 20;

    doc.setFont('helvetica', 'bold');
    doc.text('Output Figures:', margin, currentY);
    doc.setFont('helvetica', 'normal');
    doc.text(`${active.length} verified output figures`, margin + 120, currentY);
    currentY += 20;

    // Bottom banner
    doc.setFontSize(8.5);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text('Generated by Colab2Doc · 100% Client-Side Verified Report', margin, pageHeight - 35);
    doc.text(`Page ${pageNum}`, pageWidth - margin - 35, pageHeight - 35);

    pageNum++;
  }

  // Helper to load image to HTMLImageElement for aspect ratio calculation
  const loadImage = (src: string): Promise<HTMLImageElement> => {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => resolve(img);
      img.onerror = () => reject(new Error('Image load failed'));
      img.src = src;
    });
  };

  // Helper to draw a single figure in a given box
  const drawFigureBlock = async (
    item: NotebookOutputItem,
    idx: number,
    blockX: number,
    startY: number,
    blockW: number,
    maxAvailH: number
  ) => {
    let y = startY;
    const figNum = String(idx + 1).padStart(2, '0');
    const captionTitle = config.labelCaption
      ? `Figure ${figNum}: ${item.caption || 'Output'}`
      : item.caption || `Figure ${figNum}`;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(isSideBySide ? 10.5 : 12.5);
    doc.setTextColor(accentRgb[0], accentRgb[1], accentRgb[2]);
    const captionLines = doc.splitTextToSize(captionTitle, blockW);
    doc.text(captionLines, blockX, y);
    y += captionLines.length * (isSideBySide ? 13 : 15) + 2;

    // Source Reference & Metadata
    const metaParts: string[] = [];
    if (config.addCellRef) {
      metaParts.push(`Cell ${item.cellIndex + 1}, Out #${item.outputIndex + 1}`);
    }
    if (item.author) metaParts.push(item.author);
    if (item.reportDate) metaParts.push(item.reportDate);

    if (metaParts.length > 0) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(isSideBySide ? 7.5 : 8.5);
      doc.setTextColor(100, 116, 139);
      doc.text(metaParts.join(' · '), blockX, y);
      y += 12;
    }

    // Explanatory Note (if present)
    if (item.notes && item.notes.trim()) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(isSideBySide ? 7.5 : 8.5);
      doc.setTextColor(71, 85, 105);
      const noteLines = doc.splitTextToSize(`Note: ${item.notes.trim()}`, blockW - 10);
      const noteBoxHeight = noteLines.length * 10 + 8;

      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(blockX, y, blockW, noteBoxHeight, 2, 2, 'FD');
      doc.text(noteLines, blockX + 5, y + 10);
      y += noteBoxHeight + 8;
    } else {
      y += 4;
    }

    // Add Image
    if (item.src) {
      try {
        const img = await loadImage(item.src);
        const naturalW = img.naturalWidth || item.dim?.w || 800;
        const naturalH = img.naturalHeight || item.dim?.h || 600;

        const maxImgH = maxAvailH - (y - startY);
        let renderW = blockW;
        let renderH = (naturalH / naturalW) * renderW;

        if (renderH > maxImgH) {
          renderH = maxImgH;
          renderW = (naturalW / naturalH) * renderH;
        }

        const renderX = blockX + (blockW - renderW) / 2;

        doc.setFillColor(255, 255, 255);
        doc.setDrawColor(226, 232, 240);
        doc.roundedRect(renderX - 1, y - 1, renderW + 2, renderH + 2, 2, 2, 'S');

        const imgFormat = item.src.startsWith('data:image/jpeg') ? 'JPEG' : 'PNG';
        doc.addImage(item.src, imgFormat, renderX, y, renderW, renderH, undefined, 'FAST');
      } catch (e) {
        console.warn('Could not draw image to PDF:', e);
      }
    }
  };

  const drawPageHeaderAndFooter = () => {
    // Top Header Banner
    doc.setFillColor(accentRgb[0], accentRgb[1], accentRgb[2]);
    doc.rect(0, 0, pageWidth, 3, 'F');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(config.reportTitle || 'Colab2Doc Report', margin, 24);
    const shortFile = notebookFilename.length > 35 ? notebookFilename.substring(0, 32) + '...' : notebookFilename;
    doc.text(shortFile, pageWidth - margin - doc.getTextWidth(shortFile), 24);

    doc.setDrawColor(241, 245, 249);
    doc.line(margin, 28, pageWidth - margin, 28);

    // Page Footer
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.line(margin, pageHeight - 30, pageWidth - margin, pageHeight - 30);
    doc.text('Colab2Doc Verified Report', margin, pageHeight - 16);
    const pageNumText = `Page ${pageNum}`;
    doc.text(pageNumText, pageWidth - margin - doc.getTextWidth(pageNumText), pageHeight - 16);
  };

  // 2. Output Figures
  if (config.intelligentGrid) {
    // Intelligent Grid packing in PDF
    const layout = computeIntelligentLayout(active, config);
    const colGap = 16;
    const colW = (contentWidth - colGap) / 2;

    for (let rIdx = 0; rIdx < layout.rows.length; rIdx++) {
      const row = layout.rows[rIdx];
      const percent = Math.round(15 + ((rIdx + 1) / layout.rows.length) * 80);
      onProgress?.(percent, `Intelligent PDF packing row ${rIdx + 1} of ${layout.rows.length}...`);

      if (config.titlePage || rIdx > 0) {
        doc.addPage();
      }

      drawPageHeaderAndFooter();

      const startY = 46;
      const maxAvailableH = pageHeight - startY - 55;

      if (row.type === 'single') {
        const item = row.items[0];
        const itemIdx = active.indexOf(item);
        await drawFigureBlock(item, itemIdx >= 0 ? itemIdx : rIdx, margin, startY, contentWidth, maxAvailableH);
      } else {
        const itemA = row.items[0];
        const itemB = row.items[1];
        const idxA = active.indexOf(itemA);
        const idxB = active.indexOf(itemB);

        await drawFigureBlock(itemA, idxA >= 0 ? idxA : rIdx * 2, margin, startY, colW, maxAvailableH);
        if (itemB) {
          const rightX = margin + colW + colGap;
          await drawFigureBlock(itemB, idxB >= 0 ? idxB : rIdx * 2 + 1, rightX, startY, colW, maxAvailableH);
        }
      }

      pageNum++;
    }
  } else if (isSideBySide) {
    // Side-by-Side: 2 figures per page
    const colGap = 16;
    const colW = (contentWidth - colGap) / 2;

    for (let i = 0; i < active.length; i += 2) {
      const itemA = active[i];
      const itemB = i + 1 < active.length ? active[i + 1] : null;

      const percent = Math.round(15 + ((i + 1) / active.length) * 80);
      onProgress?.(percent, `Assembling side-by-side figures ${i + 1}${itemB ? ` & ${i + 2}` : ''} of ${active.length}...`);

      if (config.titlePage || i > 0) {
        doc.addPage();
      }

      drawPageHeaderAndFooter();

      const startY = 46;
      const maxAvailableH = pageHeight - startY - 55;

      // Draw Figure A (Left Column)
      await drawFigureBlock(itemA, i, margin, startY, colW, maxAvailableH);

      // Draw Figure B (Right Column) if present
      if (itemB) {
        const rightX = margin + colW + colGap;
        await drawFigureBlock(itemB, i + 1, rightX, startY, colW, maxAvailableH);
      }

      pageNum++;
    }
  } else {
    // Single Column: 1 figure per page
    for (let idx = 0; idx < active.length; idx++) {
      const item = active[idx];
      const percent = Math.round(15 + ((idx + 1) / active.length) * 80);
      onProgress?.(percent, `Assembling figure ${idx + 1} of ${active.length}...`);

      if (config.titlePage || idx > 0) {
        doc.addPage();
      }

      drawPageHeaderAndFooter();

      const startY = 46;
      const maxAvailableH = pageHeight - startY - 55;
      await drawFigureBlock(item, idx, margin, startY, contentWidth, maxAvailableH);

      pageNum++;
    }
  }

  onProgress?.(100, 'Finalizing PDF document...');
  const blob = doc.output('blob');
  return blob;
}

// Native Browser Print-to-PDF Helper
export function printCurrentReport(): void {
  window.print();
}
